# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ope_pb2 as ope__pb2


class OpeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHi = channel.unary_unary(
        '/ope.Ope/SayHi',
        request_serializer=ope__pb2.HiRequest.SerializeToString,
        response_deserializer=ope__pb2.HiReply.FromString,
        )
    self.GetCpe = channel.unary_stream(
        '/ope.Ope/GetCpe',
        request_serializer=ope__pb2.CpeRequest.SerializeToString,
        response_deserializer=ope__pb2.CpeReply.FromString,
        )
    self.GetFib = channel.unary_stream(
        '/ope.Ope/GetFib',
        request_serializer=ope__pb2.FibRequest.SerializeToString,
        response_deserializer=ope__pb2.FibReply.FromString,
        )


class OpeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SayHi(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCpe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFib(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OpeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHi': grpc.unary_unary_rpc_method_handler(
          servicer.SayHi,
          request_deserializer=ope__pb2.HiRequest.FromString,
          response_serializer=ope__pb2.HiReply.SerializeToString,
      ),
      'GetCpe': grpc.unary_stream_rpc_method_handler(
          servicer.GetCpe,
          request_deserializer=ope__pb2.CpeRequest.FromString,
          response_serializer=ope__pb2.CpeReply.SerializeToString,
      ),
      'GetFib': grpc.unary_stream_rpc_method_handler(
          servicer.GetFib,
          request_deserializer=ope__pb2.FibRequest.FromString,
          response_serializer=ope__pb2.FibReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ope.Ope', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
