# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ope.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ope.proto',
  package='ope',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tope.proto\x12\x03ope\"\x19\n\tHiRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1a\n\x07HiReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\nCpeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"{\n\x08\x43peReply\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07up_time\x18\x02 \x01(\t\x12\x0e\n\x06socket\x18\x03 \x01(\x11\x12\x0e\n\x06rx_pkt\x18\x04 \x01(\r\x12\x0f\n\x07rx_drop\x18\x05 \x01(\r\x12\x0e\n\x06tx_pkt\x18\x06 \x01(\r\x12\x0f\n\x07tx_drop\x18\x07 \x01(\r2\\\n\x03Ope\x12\'\n\x05SayHi\x12\x0e.ope.HiRequest\x1a\x0c.ope.HiReply\"\x00\x12,\n\x06GetCpe\x12\x0f.ope.CpeRequest\x1a\r.ope.CpeReply\"\x00\x30\x01\x62\x06proto3')
)




_HIREQUEST = _descriptor.Descriptor(
  name='HiRequest',
  full_name='ope.HiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ope.HiRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=43,
)


_HIREPLY = _descriptor.Descriptor(
  name='HiReply',
  full_name='ope.HiReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ope.HiReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=71,
)


_CPEREQUEST = _descriptor.Descriptor(
  name='CpeRequest',
  full_name='ope.CpeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ope.CpeRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=99,
)


_CPEREPLY = _descriptor.Descriptor(
  name='CpeReply',
  full_name='ope.CpeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ope.CpeReply.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='up_time', full_name='ope.CpeReply.up_time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='socket', full_name='ope.CpeReply.socket', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rx_pkt', full_name='ope.CpeReply.rx_pkt', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rx_drop', full_name='ope.CpeReply.rx_drop', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tx_pkt', full_name='ope.CpeReply.tx_pkt', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tx_drop', full_name='ope.CpeReply.tx_drop', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=224,
)

DESCRIPTOR.message_types_by_name['HiRequest'] = _HIREQUEST
DESCRIPTOR.message_types_by_name['HiReply'] = _HIREPLY
DESCRIPTOR.message_types_by_name['CpeRequest'] = _CPEREQUEST
DESCRIPTOR.message_types_by_name['CpeReply'] = _CPEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HiRequest = _reflection.GeneratedProtocolMessageType('HiRequest', (_message.Message,), dict(
  DESCRIPTOR = _HIREQUEST,
  __module__ = 'ope_pb2'
  # @@protoc_insertion_point(class_scope:ope.HiRequest)
  ))
_sym_db.RegisterMessage(HiRequest)

HiReply = _reflection.GeneratedProtocolMessageType('HiReply', (_message.Message,), dict(
  DESCRIPTOR = _HIREPLY,
  __module__ = 'ope_pb2'
  # @@protoc_insertion_point(class_scope:ope.HiReply)
  ))
_sym_db.RegisterMessage(HiReply)

CpeRequest = _reflection.GeneratedProtocolMessageType('CpeRequest', (_message.Message,), dict(
  DESCRIPTOR = _CPEREQUEST,
  __module__ = 'ope_pb2'
  # @@protoc_insertion_point(class_scope:ope.CpeRequest)
  ))
_sym_db.RegisterMessage(CpeRequest)

CpeReply = _reflection.GeneratedProtocolMessageType('CpeReply', (_message.Message,), dict(
  DESCRIPTOR = _CPEREPLY,
  __module__ = 'ope_pb2'
  # @@protoc_insertion_point(class_scope:ope.CpeReply)
  ))
_sym_db.RegisterMessage(CpeReply)



_OPE = _descriptor.ServiceDescriptor(
  name='Ope',
  full_name='ope.Ope',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=226,
  serialized_end=318,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHi',
    full_name='ope.Ope.SayHi',
    index=0,
    containing_service=None,
    input_type=_HIREQUEST,
    output_type=_HIREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCpe',
    full_name='ope.Ope.GetCpe',
    index=1,
    containing_service=None,
    input_type=_CPEREQUEST,
    output_type=_CPEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OPE)

DESCRIPTOR.services_by_name['Ope'] = _OPE

# @@protoc_insertion_point(module_scope)
